name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install
      uses: actions/npm@1.0.0
      with:
        args: install
    - name: Build
      uses: actions/npm@1.0.0
      with:
        args: run build
    - name: GitHub Pages Deploy
      uses: johno/actions-push-subdirectories@v0.0.1
      env:
        API_TOKEN_GITHUB: ${{ secrets.ACCESS_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: build luke142367 luke14236.github.io