name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Lint
      uses: stefanoeb/eslint-action@1.0.0
      with:
        args: 'src/**/*.tsx' 'src/**/*.ts'
    - name: Install
      uses: actions/npm@1.0.0
      with:
        args: install
    - name: Build
      uses: actions/npm@1.0.0
      with:
        args: run build
    - name: GitHub Pages Deploy
      uses: maxheld83/ghpages@v0.2.1
      env:
        BUILD_DIR: build/
        GH_PAT: ${{ secrets.ACCESS_TOKEN }}